/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Random;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRoll() {
        int[] rolls = Library.roll(3);
        //should be length of 3
        //numbers should be between 1 and 6
        Random rnd = new Random();
        int index = rnd.nextInt(rolls.length);
        assertEquals("Length of array should equal # of dice rolls", 3, rolls.length);
        assertTrue("Value at any given index should be 1-6",rolls[index] < 7 && rolls[index] > 0);
    }

    @Test public void testContainsDuplicates() {
        int[] noDupes = {1, 2, 3, 4};
        assertFalse(Library.containsDuplicates(noDupes));

        int[] dupes = {1, 2, 3, 2};
        assertTrue(Library.containsDuplicates(dupes));
    }
}
