/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant {
    public String name;
    public double stars;
    public String price;

    public Restaurant(String name, String price) {
        this.name = name;
        this.price = price;
        this.stars = 0;
    }

    public String toString() {
        return "Restaurant: " + name + " | Price: "  + price + " | Rating: " + stars;

    }
}
