import java.util.HashSet;
import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant implements Reviewable {
    public String name;
    public double stars;
    public String price;
    public Set<Review> reviews = new HashSet<>();

    public Restaurant(String name, String price) {
        this.name = name;
        this.price = price;
        this.stars = 0;
    }

    //Turns the restaurant object into a readable string
    public String toString() {
        return "Restaurant: " + name + " | Price: "  + price + " | Rating: " + stars + " | Reviews: " + reviews.size();
    }

    //Takes in a review to add for the restaurant, adds it to the HashSet of all other unique reviews, sets the reviews restaurant to the one it is added to,
    //and updates the restaurants star value
    public void addReview(Review toAdd) {
        reviews.add(toAdd);
        toAdd.location = this;
        double totalStars = 0;
        for (Review review : reviews) {
            totalStars += (double) review.stars;
        }
        stars = totalStars / (double) reviews.size();
    }

    public String getName() {
        return this.name;
    }
}
