import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        File file = new File(args[0]);
        String transform = args[2];

        try {
            BufferedImage reader = ImageIO.read(file);
            Bitmap image = new Bitmap(reader, args[1]);
            switch (transform.toLowerCase()) {
                case "flipvertical": image.flipVertical();
                                     break;
                case "fliphorizontal": image.flipHorizontal();
                                       break;
                case "convertgrayscale": image.convertGrayscale();
                                         break;
                case "darken": image.darken();
                                break;
                default: System.out.println("Invalid transform selected. Refer to the readme for available transforms and their names");
            }
        }
        catch (IOException e) {
            System.out.println(e + " Please ensure you typed the path and file name correctly.");
        }
    }
}
