import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        File image = new File(args[0]);

        try {
            BufferedImage reader = ImageIO.read(image);
            Bitmap test = new Bitmap(reader, args[1]);
            test.flipVertical();
            test.save();

        }
        catch (IOException e) {
            System.out.println(e);
        }
    }
}
