import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        File file = new File(args[0]);
        String transform = args[2];

        try {
            BufferedImage reader = ImageIO.read(file);
            Bitmap image = new Bitmap(reader, args[1]);
//            image.printColors(0);
            switch (transform.toLowerCase()) {
                case "flipvertical": image.flipVertical();
                case "fliphorizontal": image.flipHorizontal();
                case "convertgrayscale": image.convertGrayscale();
                case "darken": image.darken();
            }
//            image.printColors(0);
            image.save();

        }
        catch (IOException e) {
            System.out.println(e);
        }
    }
}
