import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Path gates = Paths.get("resources/gates.js");
        jsLinter(gates);
    }

    /*TODO: Write a method that reads a JavaScript file with a given Path, and prints an error whenever it finds a line that doesn’t end in a semi-colon.
    */

    public static void jsLinter(Path file) {
        try(BufferedReader reader = Files.newBufferedReader(file)) {
            String currentLine = "";
            int line = 0;
            while (currentLine != null) {
                if (!currentLine.isEmpty() && !currentLine.endsWith("{") && !currentLine.endsWith("}") && !currentLine.contains("if") && !currentLine.contains("else") && !currentLine.endsWith(";")) {
                    System.out.println("Line " + line + ": Missing semicolon");
                }

                line++;
                currentLine = reader.readLine();
            }
        }
        catch(IOException e) {
            System.out.println(e);
        }
    }
}
