/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    /*TODO: Write a method that reads a JavaScript file with a given Path, and prints an error whenever it finds a line that doesn’t end in a semi-colon.
    Read through the file line by line. Print an error message such as "Line 3: Missing semicolon." if a line is missing a semicolon.
    Don’t show an error if the line is empty.
    Don’t show an error if the line ends with an opening curly brace {
    Don’t show an error if the line ends with an closing curly brace }
    Don’t show an error if the line contains if or else
    Call that method in your main method on the file gates.js.
    */
}
